# Generated by Django 6.0.3 on 2026-04-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_licensekey_max_devices_licenselog_devicebinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='force_update_url',
            field=models.URLField(blank=True, help_text='URL tombol update jika versi klien lebih kecil dari Minimal Versi. Bisa link WhatsApp.', null=True, verbose_name='URL Update'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='is_maintenance',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk mengunci akses klien ini ke halaman maintenance.', verbose_name='Mode Maintenance'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='maintenance_message',
            field=models.TextField(blank=True, help_text='Pesan yang akan ditampilkan di klien. Kosongkan untuk pesan default.', null=True, verbose_name='Pesan Maintenance'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='min_app_version',
            field=models.CharField(default='v1.0', help_text='Versi minimal aplikasi klien agar bisa beroperasi. Contoh: v2.0', max_length=20, verbose_name='Minimal Versi Aplikasi'),
        ),
    ]
