# Generated by Django 6.0.3 on 2026-05-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('licenses', 'Manajemen Lisensi'), ('tenant_management', 'Tenant Management'), ('pembelian', 'Pembelian Lisensi'), ('laporan', 'Laporan'), ('ai', 'AI Manajemen'), ('user_management', 'Manajemen User'), ('access_control', 'Access Control'), ('activity_log', 'Log Aktivitas'), ('automation', 'Telegram'), ('pengaturan', 'Pengaturan')], max_length=50, verbose_name='Module'),
        ),
    ]
